version: "~> 1.0"
language: ruby
services:
- docker
stages:
- build
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: build
    name: Build
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build .
  - stage: deploy
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - nvm install v12.0.0
    - docker build . -t raimondb/opencv-dotnet-runtime-deps
    - npm install -g npm
    - npm install
    - npx semantic-release
env:
  global:
  - secure: Yzzn0ajyab4EeP9TtVgYxH/kM3pg4r5Kjgd8Pj9av11JIbeRgh8GctKqxIYzln1eo/scqURoFDgUcs7haK7i0umE2IzMCMm4SLcwObAkjI3fauL3vXOqA9GdrSxOEOynSuBgSO7WATg/xLDSroytzvy5Cs/Lsozy1/XNvzvnXyAFvcVCg8+nviqQ7v15R12TfIGFRo2RrF6lVnmRusmOVpi3lbCrG6MfDYds3F3dGGAHk2FOAYFYxLVaKvxzDfdQ2F4gv6mD6MeT97iIDksXQUqnXE3R9/JgnRuxYjLgJeoYXy9z9v0J/VpztIW6XWBioPWEcjksdN4Ck8ZVlbtjjoIMGi30DKdKq3zTKV5kAndXFCYdmW2jChS5x2e55nbhA+4QT+lsAUsJvx/6kPo8kWuAfnv21Sx2WoJ0Bx9N3d2tetPwoRaig1YvKu0/9F6cV5BAs8hd7wswfEavIJzrg4EvJzUrtov1vfENcIhi4fJp/5HXit2FJpmieaSpnXIn5XG/370MHOBnTBMUen74VyKjH4DaLpw+E5OJXWA6Sa0dzxC3S/YULkQImZcPt0a790n9L2HGCMC5IXOOUWNWlXQhGNaW3S6fbjphxiM0SoErHr7r/5tWU8vSo6zjCyh337t4n3KbPuHHsbYlMl8se0vT8T8UJVMPViQTRgF6iE8=
  - secure: o9U3mDukJ8o+sbgUajZcZJsGeq5u19iSZRgoEAHiDVUvGdDp//mHbyY7kBuaEgZhPsSZBpKHNJG1xlbQd2oXk+7NawDXkVM0KJd3iziM+40I1FQviFJagIn1P/t7So6/SPIA4uU7NG0fIoKpcQ7Rng7InaXrBO1JPNpg9V7yQhoJ8w3ADq2W9OFUjSpjg9LPD/qteXm7bfaf8DLP5t3bCfQGutOEXI+bBfSyQ9aviR8QEBS0GUoQqOUhtrziFDJfbcRbfNwcsYpNGukMHOr4WVpM/7EtMA32c0HE2y+sxu3Oh4JSYz4h7KLUSFw5IcB1PRZAXm41SDiW4IlgFsbkl3klUEK4+1rlb/l6mHL6PF1ZuFfujeV9rY+3XUwP/hhNnrAEB5XpW5c4Mlu5ZqFik2sK2ETpI2HTJFgg5V895eNZSljIq2e6AzjPx6sYu0pSq2DfWO+nZbWtonnxR5RcR2yZYS4oJGX9Ek0XjTxI+AnqCFfkF5M0KJAhcVmpLWVYNlfJvgfw6uoA8GMADR8bex+8G4o/ZK+utCyNI4oMZQGWQH8/4AT9iPXNRw3LdaegerlYnxZEQQ0GxuTXq25eedzyYawSXStntU2xzcV/KpKZylDyCMgW6d6lhjxYTHTjtKyrPxBkwLPXbDyiRVq4yLMpWDsULbgGD0FLzXpMZ0M=
