version: "~> 1.0"
language: ruby
services:
- docker
stages:
- build
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: build
    name: Build
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build .
  - stage: deploy
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - nvm install v12.0.0
    - docker build . -t raimondb/opencv-dotnet-runtime-deps
    - npm install -g npm
    - npm install
    - npx semantic-release
env:
  global:
  - secure: YKBIcmx3RT/L5IRLFFSHXdipL5UNEBq63cU5LHC4iE3LB+wppxhBRacjxs1g0R2WWtD++KKUDamSXz1KF5M7g/hZq7BeYZVlOYRqjqCqdhG0/CcairwWtjeRqpzGpPAiBaxfCE3uxouBNliF5Mm+FcZBAhHISuelxe/prR55pBLBET5WM2QY4+pBN3/WVV2QgS0yj+l2VpNBcDenlcKqOOQEGq8+DAoB2fNL4yVVUyRYzaMY2S2VVrdNyeM9gZUIYpWAPAU1Ikow6M1YbEjbmSrvuxt4DZ5mbWxPxlMriZLHlnjofnTJVZ48R+Zbtp1Ak/PYZ0R2UIajbJez/3/5tExZTwwpnexP0oKtyJrSFZ6mRoU7gI++tgAZhHgVciY8TV0ymKrGO8YeFlbzoQ3PvT+g9NBJeLepcRKGHldgEyG6nXphbU/bVumuC2kcsAVI87LAt5f7SAAnmfGvW1PfcSJAqLyE8jjvAHxHrZgZ6e/cDSZFOyp+2DlGXkOus6oN1uiKBTH4cwSUmWu/jiccmyrFB1knc2D2tc2kxHZXNounb/WUJEjAy0Tz4XfkXE1EqbfmyTN3fBRVQIWLQODRJljJGQJLqDgTV/gN0LuCPtTN8JBTUC+BJxVYixLH4CHQUu2ostD3pJegJ6IPJ249RmxwwTRPvEK2Oy8wuj980Ac=
  - secure: ydGYsAw5OKCBW4s+E0DIeS2J1Lita6MBLqGcYwJim0xsKaKXSl/sgF/DOBE0GLl6ZRUQnFAZnPoGUQ4eZTMXndPyHXE0y0IHx2TeZbjY9gmHT7fscO/Z6ZlvMedB22PIbB5aQLTyyWb5wBBA8p6FLUHI/mGATm6fOYimWCAyYeGFEvKCejC+BXihGu90lUX7Bhdv313E1rrXL3tlOQvJRJdDGlWvI4tJMD+Int4WfjFQXrwwJVGPJIuO0KeffqH7SKRxdyJ/VQTxJq3GEV6I1xoFCnElw8uF/2imgW7PI8P71dJqkDzONEZCFWr2HojQonOSlUbN0rGN0Vn7kRgFIc14e1slWucejvJ1iSOKXRovNDTsXl33tqo6TC8KAGdGoV6oduI4S0KveM+P557PPuHEGdrwgDIU9RsBsJv+xViBJFIOXMWl0sizwG6bPINlTv1Z9wfE4mnOm8mQmXugiYJlmUQFBkB00cNHZpgend52m5tHiRLsRKOf0W3F8Cqb02zRlVWdrDmvF2sRslZqcnxKZA2d3ArIXHeFZC7Lr+KCLx62g7hRES8urunfub+zEh8jSpJuR2xpdHVNJf1jGwhAFvXUoUdCZK4Blj56dxikJ2v1ZOOIpjgpfOKUYPVKFo/rBKAFhB3Mx7YGg6tjbZsHxEA1Znjv0TrmfIBaOp4=
